# Generated by Django 5.0 on 2024-01-12 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='slingID',
        ),
    ]
