# Generated by Django 5.0 on 2024-02-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_employee_slingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='working',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
