# Generated by Django 5.0 on 2024-02-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_employee_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
